apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
  name: config-service-cabundle
  namespace: drtest
