apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    description: Keeps track of changes in the application image
    openshift.io/generated-by: OpenShiftNewApp
  generation: 1
  labels:
    app: rails-pgsql-persistent
    template: rails-pgsql-persistent
  name: rails-pgsql-persistent
  namespace: drtest
spec:
  lookupPolicy:
    local: false
