apiVersion: v1
imagePullSecrets:
- name: default-dockercfg-krtd4
kind: ServiceAccount
metadata:
  name: default
  namespace: drtest
secrets:
- name: default-token-xnkg4
- name: default-dockercfg-krtd4
